package br.com.monitordenoticias.desktop

import androidx.compose.runtime.*
import br.com.monitordenoticias.android.*
import kotlinx.coroutines.*
import java.awt.Desktop
import java.io.File
import java.time.*
import java.time.format.DateTimeFormatter

class DesktopController(private val baseDir:File, private val notify:(String,String)->Unit={}):AutoCloseable{
 private val scope=CoroutineScope(SupervisorJob()+Dispatchers.Default); private val newsDb=NewsDb(File(baseDir,"data")); private val videoDb=VideoDb(File(baseDir,"data")); private val prefs=AppPreferences(File(baseDir,"data/preferences/app.properties")); private val videoStore=VideoTermStore(prefs); private val newsRepo=NewsRepository(newsDb); private val videoRepo=VideoRepository(videoDb)
 var news by mutableStateOf<List<News>>(emptyList()); var videos by mutableStateOf<List<VideoItem>>(emptyList()); var terms by mutableStateOf<List<String>>(emptyList()); var videoTerms by mutableStateOf<List<String>>(emptyList()); var demands by mutableStateOf<List<Demand>>(emptyList()); var newsHistory by mutableStateOf<List<News>>(emptyList()); var videoHistory by mutableStateOf<List<VideoItem>>(emptyList()); var newsProgress by mutableStateOf(LiveSearchProgress()); var videoProgress by mutableStateOf(LiveSearchProgress()); var newsBusy by mutableStateOf(false); var videoBusy by mutableStateOf(false); var demandBusy by mutableStateOf(false); var status by mutableStateOf("Pronto"); var videoStatus by mutableStateOf("Pronto"); var newsNewLinks by mutableStateOf<Set<String>>(emptySet()); var videoNewLinks by mutableStateOf<Set<String>>(emptySet()); var unstableVideoSources by mutableStateOf<List<VideoSourceIssue>>(emptyList()); var selectedNewsSourceIds by mutableStateOf(SourceCatalog.all.map{it.id}.toSet()); var selectedVideoSourceIds by mutableStateOf(VideoSourceCatalog.defaultIds); var newsAutomaticEnabled by mutableStateOf(prefs.getBool("NEWS_AUTO_ENABLED")); var demandAutomaticEnabled by mutableStateOf(prefs.getBool("DEMAND_AUTO_ENABLED")); var videoAutomaticEnabled by mutableStateOf(prefs.getBool("VIDEO_AUTO_ENABLED")); var automaticMonitoring by mutableStateOf(prefs.getBool("AUTOMATIC_MONITORING")); var newsIntervalMinutes by mutableStateOf(prefs.getInt("NEWS_INTERVAL",30)); var demandIntervalMinutes by mutableStateOf(prefs.getInt("DEMAND_INTERVAL",60)); var videoAutoTimes by mutableStateOf(prefs.get("VIDEO_AUTO_TIMES","08:00||12:00||18:00").split("||").filter{it.isNotBlank()}.toSet()); var totalStoredVideos by mutableStateOf(0); var capturedTodayVideos by mutableStateOf(0)
 init{DesktopEstablishedTerms.defaults.forEach(newsDb::addTerm);refresh();scope.launch{automationLoop()}}
 fun refresh(){terms=newsDb.listTerms();videoTerms=videoStore.list();demands=newsDb.listDemands();newsHistory=newsDb.listNews();videoHistory=videoDb.listAll();totalStoredVideos=videoHistory.size;val start=LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli();capturedTodayVideos=videoHistory.count{it.capturedAt>=start}}
 fun addTerm(v:String){newsDb.addTerm(v);refresh()};fun removeTerm(v:String){newsDb.removeTerm(v);refresh()};fun addVideoTerm(v:String){videoStore.save((videoTerms+v.trim()).filter{it.isNotBlank()});refresh()};fun removeVideoTerm(v:String){videoStore.save(videoTerms-v);refresh()};fun addDemand(v:String,s:String){if(v.isNotBlank()&&s.isNotBlank())newsDb.addDemand(v,s);refresh()};fun removeDemand(id:Long){newsDb.removeDemand(id);refresh()}
 fun searchNews(start:Long?=null,end:Long?=null,automatic:Boolean=false){if(newsBusy)return;scope.launch{newsBusy=true;status="Pesquisando notícias...";val e=end?:System.currentTimeMillis();val s=start?:e-24*3600_000L;val before=newsDb.links();try{val r=newsRepo.searchPeriodProgressive(s,e,SourceCatalog.selected(selectedNewsSourceIds),false){u->newsProgress=u.progress;news=u.items};newsNewLinks=r.items.map{UrlPolicy.canonicalizeUrl(it.link)}.filter{it !in before}.toSet();status="${r.items.size} encontradas • ${r.newItems} novas • ${r.errors} erros";if(r.newItems>0)notify("Monitor de Notícias","${r.newItems} novas notícias") }catch(e:Exception){status="Erro: ${e.message}"}finally{newsBusy=false;refresh()}}}
 fun searchDemand(d:Demand){if(demandBusy)return;scope.launch{demandBusy=true;try{val r=newsRepo.searchDemand(d);status="Demanda: ${r.items.size} encontrados, ${r.newItems} novos"}catch(e:Exception){status="Erro na demanda: ${e.message}"}finally{demandBusy=false;refresh()}}}
 fun searchAllDemands(){if(demandBusy)return;scope.launch{demandBusy=true;var found=0;for(d in demands.filter{it.active})runCatching{newsRepo.searchDemand(d)}.onSuccess{found+=it.items.size};status="Demandas concluídas: $found resultados";demandBusy=false;refresh()}}
 fun searchVideos(start:Long?=null,end:Long?=null,automatic:Boolean=false){if(videoBusy)return;scope.launch{videoBusy=true;videoStatus="Pesquisando vídeos...";val e=end?:System.currentTimeMillis();val s=start?:e-7*24*3600_000L;val before=videoDb.links();try{val r=videoRepo.search(s,e,VideoSourceCatalog.selected(selectedVideoSourceIds),videoTerms,demands){u->videoProgress=u.progress;videos=u.items;unstableVideoSources=u.issues};videoNewLinks=r.items.map{UrlPolicy.canonicalizeUrl(it.link)}.filter{it !in before}.toSet();videoStatus="${r.items.size} encontrados • ${r.newItems} novos • ${r.errors} erros"}catch(e:Exception){videoStatus="Erro: ${e.message}"}finally{videoBusy=false;refresh()}}}
 fun exportNewsHistoryCsv():File{val f=File(baseDir,"data/export-noticias-${System.currentTimeMillis()}.csv");f.parentFile.mkdirs();f.writeText(buildString{appendLine("Data,Título,Fonte,Link,Resumo,Termo,Demanda,Capturado em");newsHistory.forEach{appendLine(listOf(it.date?.toString()?:"",it.title,it.source,it.link,it.snippet,it.matchedTerm?:"",it.matchedDemand?:"",it.capturedAt.toString()).joinToString(",",transform=::csv))}},Charsets.UTF_8);return f}
 private fun csv(v:String)="\""+v.replace("\"","\"\"").replace("\r"," ").replace("\n"," ")+"\""
 fun parsePeriod(sd:String,st:String,ed:String,et:String):Pair<Long,Long>{val z=ZoneId.systemDefault();val df=DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");return LocalDateTime.parse("$sd $st",df).atZone(z).toInstant().toEpochMilli() to LocalDateTime.parse("$ed $et",df).atZone(z).toInstant().toEpochMilli()}
 fun addVideoAutoTime(v:String):Boolean=runCatching{LocalTime.parse(v);videoAutoTimes=videoAutoTimes+v;prefs.put("VIDEO_AUTO_TIMES",videoAutoTimes.sorted().joinToString("||"));true}.getOrDefault(false);fun removeVideoAutoTime(v:String){videoAutoTimes=videoAutoTimes-v;prefs.put("VIDEO_AUTO_TIMES",videoAutoTimes.sorted().joinToString("||"))}
 private suspend fun automationLoop(){var ln=0L;var ld=0L;var lv="";while(scope.isActive){if(automaticMonitoring){val now=System.currentTimeMillis();if(newsAutomaticEnabled&&!newsBusy&&now-ln>=newsIntervalMinutes*60_000L){ln=now;searchNews(automatic=true)};if(demandAutomaticEnabled&&!demandBusy&&now-ld>=demandIntervalMinutes*60_000L){ld=now;searchAllDemands()};val slot=LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm"));if(videoAutomaticEnabled&&slot in videoAutoTimes&&slot!=lv&&!videoBusy){lv=slot;searchVideos(automatic=true)}};delay(30_000)}}
 fun openUrl(url:String){runCatching{Desktop.getDesktop().browse(java.net.URI(url))}}
 override fun close(){scope.cancel();newsDb.close();videoDb.close()}
}
