package br.com.monitordenoticias.desktop

import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.*
import br.com.monitordenoticias.android.*
import java.io.File
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

fun main()=application{val base=File(System.getProperty("user.dir"));val c=remember{DesktopController(base)};Window(onCloseRequest={c.close();exitApplication()},title="Monitor de Notícias v4.0.2 - Clean Room"){MaterialTheme{App(c)}}}
@Composable fun App(c:DesktopController){var tab by remember{mutableStateOf("INÍCIO")};Row(Modifier.fillMaxSize()){Column(Modifier.width(190.dp).fillMaxHeight().background(MaterialTheme.colors.surface).padding(12.dp)){Text("MONITOR DE NOTÍCIAS",style=MaterialTheme.typography.h6);Spacer(Modifier.height(16.dp));listOf("INÍCIO","NOTÍCIAS","VÍDEOS","TERMOS","DEMANDAS","FONTES","HISTÓRICO","CONFIGURAÇÕES").forEach{Button(onClick={tab=it},modifier=Modifier.fillMaxWidth().padding(vertical=3.dp)){Text(it)}}};Box(Modifier.fillMaxSize().padding(16.dp)){when(tab){"INÍCIO"->Home(c);"NOTÍCIAS"->NewsScreen(c);"VÍDEOS"->VideosScreen(c);"TERMOS"->TermsScreen(c);"DEMANDAS"->DemandsScreen(c);"FONTES"->SourcesScreen(c);"HISTÓRICO"->HistoryScreen(c);else->SettingsScreen(c)}}}}
@Composable fun Home(c:DesktopController){Column{Text("Painel",style=MaterialTheme.typography.h4);Spacer(Modifier.height(10.dp));Text("Notícias salvas: ${c.newsHistory.size}");Text("Vídeos salvos: ${c.totalStoredVideos}");Text("Vídeos capturados hoje: ${c.capturedTodayVideos}");Text("Demandas: ${c.demands.size}");Spacer(Modifier.height(12.dp));Text(c.status);Text(c.videoStatus);if(c.unstableVideoSources.isNotEmpty())Text("Fontes de vídeo com falha: ${c.unstableVideoSources.size}")}}
@Composable fun NewsScreen(c:DesktopController){Column{Row{Button(onClick={c.searchNews() },enabled=!c.newsBusy){Text(if(c.newsBusy)"PESQUISANDO..." else "PESQUISAR ÚLTIMAS 24H")};Spacer(Modifier.width(12.dp));Text(c.status)};Spacer(Modifier.height(8.dp));LazyColumn{items(c.news.ifEmpty{c.newsHistory}){n->Card(Modifier.fillMaxWidth().padding(vertical=4.dp),elevation=2.dp){Column(Modifier.padding(10.dp)){Text(n.title,style=MaterialTheme.typography.subtitle1);Text("${n.source} • ${fmt(n.date)}");if(n.matchedTerm!=null)Text("Termo: ${n.matchedTerm}");if(UrlPolicy.canonicalizeUrl(n.link) in c.newsNewLinks)Text("NOVO");TextButton(onClick={c.openUrl(n.link)}){Text("ABRIR")}}}}}}}
@Composable fun VideosScreen(c:DesktopController){Column{Row{Button(onClick={c.searchVideos()},enabled=!c.videoBusy){Text(if(c.videoBusy)"PESQUISANDO..." else "PESQUISAR VÍDEOS")};Spacer(Modifier.width(12.dp));Text(c.videoStatus)};LazyColumn{items(c.videos.ifEmpty{c.videoHistory}){v->Card(Modifier.fillMaxWidth().padding(vertical=4.dp),elevation=2.dp){Column(Modifier.padding(10.dp)){Text(v.title);Text(v.sourceName);if(v.relevant)Text("Termo: ${v.matchedTerm}");if(v.demand)Text("Demanda: ${v.matchedDemand}");TextButton(onClick={c.openUrl(v.link)}){Text("ABRIR")}}}}}}}
@Composable fun TermsScreen(c:DesktopController){var n by remember{mutableStateOf("")};var v by remember{mutableStateOf("")};Row{Column(Modifier.weight(1f)){Text("TERMOS DE NOTÍCIAS");Row{TextField(n,{n=it});Button({c.addTerm(n);n=""}){Text("Adicionar")}};c.terms.forEach{Row{Text(it,Modifier.weight(1f));TextButton({c.removeTerm(it)}){Text("Remover")}}}};Spacer(Modifier.width(20.dp));Column(Modifier.weight(1f)){Text("TERMOS DE VÍDEOS");Row{TextField(v,{v=it});Button({c.addVideoTerm(v);v=""}){Text("Adicionar")}};c.videoTerms.forEach{Row{Text(it,Modifier.weight(1f));TextButton({c.removeVideoTerm(it)}){Text("Remover")}}}}}}
@Composable fun DemandsScreen(c:DesktopController){var vehicle by remember{mutableStateOf("")};var subject by remember{mutableStateOf("")};Column{Row{TextField(vehicle,{vehicle=it},label={Text("Veículo")});Spacer(Modifier.width(8.dp));TextField(subject,{subject=it},label={Text("Assunto")});Button({c.addDemand(vehicle,subject);vehicle="";subject=""}){Text("Adicionar")}};Button({c.searchAllDemands()},enabled=!c.demandBusy){Text("PESQUISAR TODAS")};c.demands.forEach{Card(Modifier.fillMaxWidth().padding(4.dp)){Row(Modifier.padding(8.dp)){Column(Modifier.weight(1f)){Text("${it.vehicle} + ${it.subject}");Text("Encontrados: ${it.lastFoundCount} • Novos: ${it.lastNewCount}")};TextButton({c.searchDemand(it)}){Text("Pesquisar")};TextButton({c.removeDemand(it.id)}){Text("Excluir")}}}}}}
@Composable fun SourcesScreen(c:DesktopController){Column{Text("FONTES DE NOTÍCIAS",style=MaterialTheme.typography.h6);SourceCatalog.all.forEach{s->Row{Checkbox(s.id in c.selectedNewsSourceIds,{on->c.selectedNewsSourceIds=if(on)c.selectedNewsSourceIds+s.id else c.selectedNewsSourceIds-s.id});Text("${s.name} (${s.region}${s.state?.let{"/$it"}?:""})")}};Spacer(Modifier.height(12.dp));Text("FONTES DE VÍDEOS",style=MaterialTheme.typography.h6);VideoSourceCatalog.all.forEach{s->Row{Checkbox(s.id in c.selectedVideoSourceIds,{on->c.selectedVideoSourceIds=if(on)c.selectedVideoSourceIds+s.id else c.selectedVideoSourceIds-s.id});Text(s.name)}}}}
@Composable fun HistoryScreen(c:DesktopController){Column{Button({val f=c.exportNewsHistoryCsv();c.status="CSV exportado: ${f.absolutePath}"}){Text("EXPORTAR NOTÍCIAS CSV")};Text(c.status);Text("Histórico: ${c.newsHistory.size} notícias / ${c.videoHistory.size} vídeos")}}
@Composable fun SettingsScreen(c:DesktopController){Column{Text("AUTOMAÇÃO",style=MaterialTheme.typography.h6);Row{Checkbox(c.automaticMonitoring,{c.automaticMonitoring=it});Text("Monitoramento automático")};Row{Checkbox(c.newsAutomaticEnabled,{c.newsAutomaticEnabled=it});Text("Notícias a cada ${c.newsIntervalMinutes} min")};Row{Checkbox(c.demandAutomaticEnabled,{c.demandAutomaticEnabled=it});Text("Demandas a cada ${c.demandIntervalMinutes} min")};Row{Checkbox(c.videoAutomaticEnabled,{c.videoAutomaticEnabled=it});Text("Vídeos nos horários: ${c.videoAutoTimes.sorted().joinToString()}")};Spacer(Modifier.height(10.dp));Text("Proxy e inicialização do Windows possuem classes auxiliares e podem ser configurados no código/registro nesta versão do repositório.")}}
private fun fmt(v:Long?)=v?.let{DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm").withZone(ZoneId.systemDefault()).format(Instant.ofEpochMilli(it))}?:"sem data"
